name: CI/CD Install Build and Test

on:
  push:
    branches:
      - main
      - master
      - development
      - ci/cd-workflows

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout repository'
        uses: actions/checkout@v3

      - name: 'setup node'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'install npm@latest'
        run: npm i -g npm@latest

      - name: 'install dependencies'
        uses: bahmutov/npm-install@v1

      - name: 'Run tests'
        run: npm run test --if-present

      - name: Build
        run: npm run build
